### ISSUE TITLE
How to setup svelte page template layout inside /assets/js/ folder.

### ISSUE THREAD

**Issue by ajayhada** [sailscastshq/create-sails#2]
I was trying to use the svelte with sailsjs, it worked perfectly for most of the things but I am facing challenges in setting us layout with sails project, when i create Layout.svelte file, every page shows the template without content.

**Comment by ajayhada** [comment]
how to configure layout here in this folder **create-sails/template/config/svelte/assets/js/** ? 
I tried this https://inertiajs.com/pages to setup the layout, it was loading the layout for all mapped routes but not rendering the page content..

**Comment by DominusKelvin** [comment]
@ajayhada did you have any errors in your console?

**Comment by DominusKelvin** [comment]
Also, perhaps you can show how you set the layout file in reference to the guide in the Inertia docs when the tab is set to Svelte.

https://inertiajs.com/pages
